import React from "react";
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  Calendar,
  CheckCircle2,
  MapPin,
  Clock,
  ShieldAlert,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

const DetectionLogs = ({ detectionLogs = [] }) => {
  const navigate = useNavigate();

  const getAlertClass = (level) => {
    switch (level) {
      case "CRITICAL":
        return "border-red-500/20 bg-red-500/10 text-red-400";

      case "HIGH":
        return "border-orange-500/20 bg-orange-500/10 text-orange-400";

      case "MEDIUM":
        return "border-amber-500/20 bg-amber-500/10 text-amber-400";

      default:
        return "border-emerald-500/20 bg-emerald-500/10 text-emerald-400";
    }
  };

  const getIconClass = (level) => {
    switch (level) {
      case "CRITICAL":
        return "bg-red-500/10 text-red-400";

      case "HIGH":
        return "bg-orange-500/10 text-orange-400";

      case "MEDIUM":
        return "bg-amber-500/10 text-amber-400";

      default:
        return "bg-emerald-500/10 text-emerald-400";
    }
  };

  const getAnimalClass = (animal) => {
    if (animal === "No Threat") {
      return "text-emerald-400";
    }

    if (animal === "Human intruder") {
      return "text-red-400";
    }

    return "text-slate-100";
  };

  return (
    <div className="space-y-5">

      {/* HEADER */}

      <section className="rounded-2xl border border-slate-800 bg-slate-950/70">

        <div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between">

          <div className="flex items-center gap-3">

            <button
              type="button"
              onClick={() => navigate("/")}
              className="grid size-9 shrink-0 place-items-center rounded-lg border border-slate-800 bg-slate-900 text-slate-400 transition hover:border-slate-700 hover:text-slate-200"
            >
              <ArrowLeft size={16} />
            </button>

            <div className="grid size-10 place-items-center rounded-xl bg-red-500/10 text-red-400">
              <Activity size={18} />
            </div>

            <div>
              <h1 className="text-lg font-bold text-slate-100">
                Wildlife Detection Logs
              </h1>

              <p className="mt-1 text-[10px] text-slate-500">
                Complete history of AI and sensor wildlife detections
              </p>
            </div>

          </div>

          <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-center">

            <p className="text-[9px] font-bold uppercase tracking-wider text-emerald-400">
              Total Detections
            </p>

            <p className="mt-1 text-xl font-bold text-slate-100">
              {detectionLogs.length}
            </p>

          </div>

        </div>

      </section>


      {/* LOGS */}

      <section className="overflow-hidden rounded-xl border border-slate-800 bg-slate-950/60">

        <div className="border-b border-slate-800 px-4 py-3">

          <div className="flex items-center gap-2">

            <div className="grid size-8 place-items-center rounded-lg bg-emerald-500/10 text-emerald-400">
              <ShieldAlert size={15} />
            </div>

            <div>
              <h2 className="text-xs font-bold text-slate-200">
                All Detection Records
              </h2>

              <p className="text-[9px] text-slate-500">
                Every wildlife prediction received by WildGuard
              </p>
            </div>

          </div>

        </div>


        {detectionLogs.length === 0 ? (

          <div className="flex min-h-[350px] flex-col items-center justify-center px-5 text-center">

            <div className="mb-4 grid size-14 place-items-center rounded-full bg-slate-900 text-slate-600">
              <Activity size={25} />
            </div>

            <h3 className="text-sm font-semibold text-slate-300">
              No detections yet
            </h3>

            <p className="mt-2 max-w-md text-xs leading-5 text-slate-500">
              Wildlife predictions generated by the AI detection
              system will appear here automatically.
            </p>

          </div>

        ) : (

          <div className="divide-y divide-slate-900">

            {detectionLogs.map((detection, index) => (

              <div
                key={detection.id || index}
                className="p-4 transition hover:bg-slate-900/40"
              >

                <div className="flex flex-col gap-4 lg:flex-row lg:items-center">

                  {/* ICON */}

                  <div
                    className={`grid size-10 shrink-0 place-items-center rounded-xl ${getIconClass(
                      detection.level
                    )}`}
                  >

                    {detection.animal === "No Threat" ? (
                      <CheckCircle2 size={18} />
                    ) : (
                      <AlertTriangle size={18} />
                    )}

                  </div>


                  {/* MAIN DETAILS */}

                  <div className="min-w-0 flex-1">

                    <div className="flex flex-wrap items-center gap-2">

                      <h3
                        className={`text-sm font-bold ${getAnimalClass(
                          detection.animal
                        )}`}
                      >
                        {detection.animal ||
                          detection.species ||
                          "Unknown Wildlife"}
                      </h3>

                      <span
                        className={`rounded border px-2 py-0.5 text-[8px] font-bold ${getAlertClass(
                          detection.level
                        )}`}
                      >
                        {detection.level || "LOW"}
                      </span>

                    </div>


                    <div className="mt-2 flex flex-wrap gap-x-5 gap-y-2 text-[10px] text-slate-500">

                      <span className="flex items-center gap-1.5">
                        <MapPin size={11} />
                        {detection.location ||
                          "Unknown Location"}
                      </span>

                      <span className="flex items-center gap-1.5">
                        <Calendar size={11} />
                        {detection.date ||
                          formatDate(detection.timestamp)}
                      </span>

                      <span className="flex items-center gap-1.5">
                        <Clock size={11} />
                        {detection.time ||
                          formatTime(detection.timestamp)}
                      </span>

                    </div>

                  </div>


                  {/* CONFIDENCE */}

                  <div className="shrink-0 rounded-lg border border-slate-800 bg-slate-900/70 px-4 py-2 text-center">

                    <p className="text-[8px] uppercase tracking-wider text-slate-500">
                      AI Confidence
                    </p>

                    <p className="mt-1 text-sm font-bold text-slate-200">
                      {detection.confidence || "0%"}
                    </p>

                  </div>

                </div>


                {/* CAMERA */}

                <div className="mt-3 flex flex-wrap items-center gap-4 border-t border-slate-900 pt-3 text-[9px] text-slate-600">

                  <span>
                    Detection ID:{" "}
                    <span className="text-slate-500">
                      {detection.id || "N/A"}
                    </span>
                  </span>

                  <span>
                    Camera:{" "}
                    <span className="text-slate-500">
                      {detection.cameraName || "AI Camera"}
                    </span>
                  </span>

                </div>

              </div>

            ))}

          </div>

        )}

      </section>

    </div>
  );
};


/*
|--------------------------------------------------------------------------
| DATE HELPERS
|--------------------------------------------------------------------------
*/

const formatDate = (timestamp) => {
  if (!timestamp) {
    return "Unknown date";
  }

  return new Date(timestamp).toLocaleDateString();
};


const formatTime = (timestamp) => {
  if (!timestamp) {
    return "Unknown time";
  }

  return new Date(timestamp).toLocaleTimeString();
};


export default DetectionLogs;